name: betonchel_manager
description: 'Manager application for Betonchel'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.2.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  logger: ^2.2.0
  intl: ^0.19.0
  auto_route: ^8.0.3
  get_it: ^7.6.0
  injectable: ^2.1.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.0.0
  synchronized: ^3.1.0
  expandable: ^5.0.1
  collection: ^1.17.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0
  lottie: ^3.1.0
  quiver: ^3.2.1
  flutter_xlider: ^3.5.0
  cached_network_image: ^3.3.0
  async: ^2.11.0
  bloc: ^8.1.2
  sliver_tools: ^0.2.12
  provider: ^6.0.5
  rxdart: ^0.27.7
  infinite_scroll_pagination: ^4.0.0
  web_socket_channel: ^2.4.0
  url_launcher: ^6.2.3
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  responsive_framework: ^1.4.0
  skeletonizer: ^1.1.1
  collapsible_sidebar: ^2.0.7
  signalr_netcore: ^1.3.7
  omni_datetime_picker: ^1.1.0
  flutter_context_menu: ^0.1.3
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.1
  firebase_messaging: ^14.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  lints: ^3.0.0
  retrofit_generator: ^8.1.0
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

