///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsAdd = 'assets/icons/add.svg';
  static const String iconsAddCircle = 'assets/icons/add_circle.svg';
  static const String iconsArrowDown = 'assets/icons/arrow_down.svg';
  static const String iconsBox = 'assets/icons/box.svg';
  static const String iconsCheck = 'assets/icons/check.svg';
  static const String iconsCross = 'assets/icons/cross.svg';
  static const String iconsDelivery = 'assets/icons/delivery.svg';
  static const String iconsDocs = 'assets/icons/docs.svg';
  static const String iconsExclamationMark = 'assets/icons/exclamation_mark.svg';
  static const String iconsLeave = 'assets/icons/leave.svg';
  static const String iconsLetter = 'assets/icons/letter.svg';
  static const String iconsNotifications = 'assets/icons/notifications.svg';
  static const String iconsPencil = 'assets/icons/pencil.svg';
  static const String iconsPlus = 'assets/icons/plus.svg';
  static const String iconsTrashBlankAltSvgrepoCom = 'assets/icons/trash-blank-alt-svgrepo-com.svg';
  static const String iconsVan = 'assets/icons/van.svg';
  static const String imagesLogo = 'assets/images/logo.png';

}
