name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build_and_deploy_web:
    runs-on: ubuntu-latest
    steps:
      - name: Install fvm
        run: curl -fsSL https://fvm.app/install.sh | bash
      - name: Download or check flutter by fvm
        run: |
          cd ${{ github.workspace }}
          fvm install
      - name: Build web application
        run: fvm flutter build web